# ==========================================================================
# ZenithMemoryConfig.cmake
# ==========================================================================
# CMake package configuration file.
#
# This file is installed alongside the library and loaded when another
# project calls:
#
#   find_package(ZenithMemory REQUIRED)
#
# It imports the ZenithMemoryTargets.cmake file which defines the
# Zenith::Memory imported target with all include paths and link
# dependencies already set.
# ==========================================================================

@PACKAGE_INIT@

include(CMakeFindDependencyMacro)

# ZenithMemory has no external dependencies — it only uses the C++ stdlib.
# If we ever add dependencies (e.g., threading), we'd add:
#   find_dependency(Threads REQUIRED)

# Import the targets file generated by install(EXPORT ...)
include("${CMAKE_CURRENT_LIST_DIR}/ZenithMemoryTargets.cmake")
